#!/bin/bash

cp -r ~/Themes/Carbon/. ~/ &&
wal -i ~/Wallpaper/a_road_going_through_a_desert.jpeg && wal --theme ~/.cache/wal/e-ink.json
(echo -e "[Theme]\nCurrent=Carbon" | sudo -n tee /etc/sddm.conf.d/theme.conf || true) &&
~/.spicetify/spicetify config current_theme ""
~/.spicetify/spicetify apply 

cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=Papirus
gtk-font-name=JetBrains Mono 10
EOF

pkill dunst && dunst &
qtile cmd-obj -o cmd -f restart
