#!/bin/bash

cp -r ~/Themes/Cozy/. ~/ &&
wal -b 282738 -i ~/Wallpaper/Aesthetic2.png &&
(echo -e "[Theme]\nCurrent=Cozy" | sudo -n tee /etc/sddm.conf.d/theme.conf || true) &&
~/.spicetify/spicetify config current_theme text color_scheme Cozy
~/.spicetify/spicetify apply 

cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Cozy-clean
gtk-icon-theme-name=Cozy_Icons_blue
gtk-font-name=JetBrains Mono 10
EOF

pkill dunst && dunst &
qtile cmd-obj -o cmd -f restart
