#!/bin/bash

cp -r ~/Themes/Natura/. ~/ &&
wal -i ~/Wallpaper/claudio-testa-FrlCwXwbwkk-unsplash.jpg &&
(echo -e "[Theme]\nCurrent=Natura" | sudo -n tee /etc/sddm.conf.d/theme.conf || true) &&
~/.spicetify/spicetify config current_theme text color_scheme natura
~/.spicetify/spicetify apply 

cat > ~/.config/gtk-3.0/settings.ini <<EOF
[Settings]
gtk-theme-name=Natura-Clean
gtk-icon-theme-name=Natura-Icons
gtk-font-name=JetBrains Mono 10
EOF

pkill dunst && dunst &
qtile cmd-obj -o cmd -f restart
