; note: most of the accent colors are set to the green of that color scheme, feel free to change it to your preferred color

[everforest]

main           = 232A2E
sidebar        = 353f44 
player         = 0000ff
card           = 232a2e 
shadow         = 262f33 
selected-row   = ff0000
button         = d3c6aa 
button-active  = d3c6aa 
text           = 86918a
subtext        = b3b3b3


[sakura]

main           = 282738
sidebar        = 353446 
player         = 17151f
card           = 17151f 
shadow         = 262f33 
selected-row   = ff0000
button         = a97387   
button-active  = e4c7b5   
text           = e5b9c6   
subtext        = b3b3b3


[natura]

main=0F1212
sidebar        = 1c1e1e 
player         = 1c1e1e 
card           = 232a2e 
shadow         = 161818 
selected-row   = ff0000
button         = 607767   
button-active  = 607767   
text           = 607767
subtext        = b3b3b3

[cozy]

main           = 282738
sidebar        = 353446 
player         = 17151f
card           = 17151f 
shadow         = 262f33 
selected-row   = ff0000
button         = 91b1f0   
button-active  = caa9e0   
text           = 91b1f0   
subtext        = b3b3b3

